{% set name = "embree3" %}
{% set version = "3.4.0" %}
{% set sha256 = "22229f19332d4fd08eb3bf60198211bda674f51632b977c9d7fd09531e09dd8d" %}

package:
  name: {{ name }}
  version: "{{ version }}"

source:
  fn: {{ version }}.tar.gz
  url: https://github.com/embree/embree/archive/v{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  # upstream supports visual studio 13+
  skip: true  # [win and vc<13]]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - cmake

  host:
    - tbb
    - tbb-devel

  run:
    - tbb

test:
  commands:
    - test -f "${PREFIX}/lib/libembree3${SHLIB_EXT}"  # [not win]

about:
  home: https://embree.github.io/
  license: Apache 2.0
  license_file: LICENSE.txt
  summary: High Performance Ray Tracing Kernels

extra:
  recipe-maintainers:
    - joaander
