{% set name = "embree3" %}
{% set version = "3.5.0" %}
{% set sha256 = "4635439c277d0f688f1a21ad13ad22fdadbcbca04680cce346c88179b9522741" %}

package:
  name: {{ name }}
  version: "{{ version }}"

source:
  fn: {{ version }}.tar.gz
  url: https://github.com/embree/embree/archive/v{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  # upstream supports visual studio 13+
  skip: true  # [win and vc<13]]

requirements:
  build:
    - {{ compiler('cxx') }}
    - cmake

  host:
    - tbb
    - tbb-devel

  run:
    - tbb

test:
  commands:
    - test -f "${PREFIX}/lib/libembree3${SHLIB_EXT}"  # [not win]

about:
  home: https://embree.github.io/
  license: Apache 2.0
  license_file: LICENSE.txt
  summary: High Performance Ray Tracing Kernels

extra:
  recipe-maintainers:
    - joaander
