{% set name = "embree3" %}
{% set version = "4.3.3" %}
{% set sha256 = "8a3bc3c3e21aa209d9861a28f8ba93b2f82ed0dc93341dddac09f1f03c36ef2d" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  fn: {{ version }}.tar.gz
  url: https://github.com/embree/embree/archive/v{{ version }}.tar.gz
  sha256: {{ sha256 }}
  patches:
    - use-conda-forge-ABI.patch

build:
  number: 0
  # upstream supports visual studio 13+
  skip: true  # [win and vc<13]]

requirements:
  build:
    - {{ compiler('cxx') }}
    - {{ stdlib("c") }}
    - cmake
    - make  # [linux64]

  host:
    - tbb
    - tbb-devel

  run:
    - tbb

test:
  commands:
    - test -f "${PREFIX}/lib/libembree3${SHLIB_EXT}"  # [not win]

about:
  home: https://embree.github.io/
  license: Apache-2.0
  license_file: LICENSE.txt
  summary: High Performance Ray Tracing Kernels

extra:
  recipe-maintainers:
    - joaander
