{% set name = "embree3" %}
{% set version = "3.2.1" %}
{% set sha256 = "c153879e8d672742a0e8fb7df64c35060ba06e85deec3c52bd92b2c7c1aa540c" %}

package:
  name: {{ name }}
  version: "{{ version }}"

source:
  fn: {{ version }}.tar.gz
  url: https://github.com/embree/embree/archive/v{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  # upstream supports visual studio 13+
  skip: true  # [win and vc<13]]

requirements:
  build:
    - {{ compiler('cxx') }}
    - cmake

  host:
    - tbb

  run:
    - tbb

test:
  commands:
    - test -f "${PREFIX}/lib/libembree3${SHLIB_EXT}"  # [not win]

about:
  home: https://embree.github.io/
  license: Apache 2.0
  license_file: LICENSE.txt
  summary: High Performance Ray Tracing Kernels

extra:
  recipe-maintainers:
    - joaander
