{% set name = "embree3" %}
{% set version = "3.13.2" %}
{% set sha256 = "dcda827e5b7a606c29d00c1339f1ef00f7fa6867346bc46a2318e8f0a601c6f9" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  fn: {{ version }}.tar.gz
  url: https://github.com/embree/embree/archive/v{{ version }}.tar.gz
  sha256: {{ sha256 }}
  patches:
    - use-conda-forge-ABI.patch

build:
  number: 0
  # upstream supports visual studio 13+
  skip: true  # [win and vc<13]]

requirements:
  build:
    - {{ compiler('cxx') }}
    - cmake

  host:
    - tbb
    - tbb-devel

  run:
    - tbb

test:
  commands:
    - test -f "${PREFIX}/lib/libembree3${SHLIB_EXT}"  # [not win]

about:
  home: https://embree.github.io/
  license: Apache-2.0
  license_file: LICENSE.txt
  summary: High Performance Ray Tracing Kernels

extra:
  recipe-maintainers:
    - joaander
