travis:
  secure:
    BINSTAR_TOKEN: D8Dtec2akuW0xaxfJpNbDIOwae9NxIReHDADXZaddzQ42N7rVEBXz/R4lUHQaRY9JSZmiFJtc5ZsVYcdqAqXIn8KvdI+2Yzq/eQLk6KnRc0HZZCI+TyBrg3d4P772UJFlKjmdpk2NIOdJmGAeuYST4+uwN7j4WWP3hYqO6OHAvtaecxEjzMr3fgR0rGAZqIel2yEOYSZ8DZ8MdKDM0sc5vfLJS/EY2OKtDlWOejhwlIUraCefbFSEYkCVBGjmTUkKw6jItcGyQxOYBgbevOoe/hyqfNeir4RZY+1gqN6dX+Qyj+TOto5EW4TS+ybyBDxl4zsKEchZo3656hXDOwP2uBZgDnu1dsD+xU8c+6A/s1ISO3fdsT42B5vKFglaZF/yCpJWtcd9qf7eOU+/bXdPROVK/8M+XKC9SOWyVDwhI7kEuSjlMc8wd3rfgZeT1uWpwbT8DaAHC/ncOHK+EGtsQuN2EbwCa6UaIhevNM3FQaGUJAJjsYn+eM8F6tASZz1b+VIeOu25CwIn1CuQXCx/4GCLiSgUNYpLSGEsYAxEx3n4ff38cWYOULSzEwWlsjvCjipjPZRSQBcBgz1HO02hy88I2Abi0Yszn18REIY0mjXoGC1TYFGWTQbE35s+2NRSaztLcioyeX7156h2Mw3laGThyzcxRjKpKiIXCWUaxc=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
