travis:
  secure:
    BINSTAR_TOKEN: K7dpTSK+vZQAcL61qYDiRKaD4zpdawq7Pk+g89cKeZJ8mCoJ8u24e665xxenYk1aLB7Awx04G/yOJ1e54zLp7ji5d++K3ElCFWSrsuH1XTHWYh5F1iiFmqGtln+e7ltR57dt0PfVOXg0xWrH72FKqG/DT4Bcv6w94pz9aP94a9onaDEoSbohWk8Zf86IZdlOX+z6wVLAq6U8GkNnkf8PwdB8BZs4OqDhN7KGD4xBOhcmNOem/8Yw814bx1FozY3xE+Yv/E9DxIX2oP/d0Eg5XOqJH8/VpnU+x6FKfYF7cuoBNCvUezyixtEoLXgqSH5bSiwk5qBjq4Jc6H629ifEb5YZ6Lnir7MMRTjk9AV6laM9nMa+Rx6iIzaim0l8kLnRuQxThOnWtioboUH+PSLeKp+zqNry5roslciWIBAOazsWuL2Q98MGFU1lB3TDjGtdpRQD8BzV0jUXgDCPQQvRXg9MBy9TehoXv+cGac4siF625QyWoAbxACpZj9X/uujYK2t2cZCIgSlywIe+cyPEUYsBSbbpoTEdfhMFFz11c0JuDh7emfYbDckQRTZcC6KYsul/Df36ym3b0hh4JbG3z8yrf0PrJb7/ZL1JDepjp6mLLoRIYB+br3xiYNodPleoj2Eiad1/EgSLuyptG1VxTDLosh64QdGxa/Cppw52usg=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
