appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
travis:
  secure: {BINSTAR_TOKEN: MWui2AtkIZtAJo0bqmJvvfqIeLuB5HWpRcl8YvkoFBm0SghpZ5Hwk3el2YrIIckuNqNIrbB1k3bbBsQIcBjBJXNJ2K7QB8zrmqkvF/TeYV1fIxqxhZhStgGmhXwSmN2ZrITkNb7z+ozg8AsabM285aCXfedDeQDY6SZbhYiKuFiuKHLhmnGMoYJWsseztUd4HKl+Uihe/9OZzGciLJN7za0vO+pC7gdT0N63bvbrb7R8fN7x31DNQ4HG0UhpNjFtu9fSZdG0F2ZFUj0nwaZXbdhLUlDvi6zvr6BvizbDB97H8z37mm6wajxQ28kptkhMGLvDmsH5nTkJgejlSI4SXIi7CyqtuRaGaViOLqwLzM6PaAOZ2PtdjrnbQoYke9xGLh631mgRgdjP8EVIdWBg1hOfqK0k22VhXGbA7A7CrdNPcZ0lb2SnuP6g/XylxXFj0FKzQTSsBEgR60XkbJTri2ygtfbPt76GBeyZyHxDG9iY0KyVL0i+GMkOtHmq1Kg4kR9Y/OCSpVHl6Bpv9G1DzwBAYduC4IZksrMiTIV6RKXiEO9B/0J8U7ssiaZIy9bzB9pA1i7SeAOtoQSMoSDogjpzkdk4NAALISHnupIC6EuO2NlKQiIAEM46MPcHJDaifivNMP1RRf7QK/JO76oEv++VDvogTOrhQREGfohivxU=}
provider:
  win: azure
conda_forge_output_validation: true
